name: Go

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: cd /home/runner/work/galaga/galaga/awesomeProject/game && pwd && ls -a && go test -v ./...
